In [2]:
# Import libraries
import numpy as np
from sklearn.svm import SVC
from scipy.io import loadmat
import imbalance_metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

We use a popular hyperspectral dataset for experimentation in this work, available at [Salinas-A scene](http://www.ehu.eus/ccwintco/index.php?title=Hyperspectral_Remote_Sensing_Scenes#Salinas-A_scene).

In [3]:
# Load dataset
salinas = loadmat('SalinasA_corrected.mat')
dataset = salinas['salinasA_corrected']

# Load labels (ground truth)
gt = loadmat('SalinasA_gt.mat')
ground_truth = gt['salinasA_gt']

# Dataset shape 
height, width, bands = dataset.shape

# Normalized dataset
dataset = dataset/10000

In [4]:
x = np.reshape(dataset, (height*width, bands))
y = np.reshape(ground_truth, -1)

result = np.where(y != 0)[0]
x = x[result,:]
y =y[result]

# Split training and testing data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.90)

# Svm classifier
svclassifier = SVC(kernel='linear')
svclassifier.fit(x_train, y_train)
y_pred = svclassifier.predict(x_test)

In [5]:
# Confusion matrix
Cm = confusion_matrix(y_test, y_pred)
print(Cm)

# Report funcition imbalance metrics
imbalance_metrics.report(y_test,y_pred)

[[ 353    0    0    1    0    0]
 [   0 1042   26   26   86   22]
 [   0  172  342   30    0    0]
 [   0    3    0 1383    0    0]
 [   0    0    0    0  596    2]
 [   0    0    0    0   15  715]]
----------------------------------- Score -----------------------------------
Class        PRC          NPV          ACC          F1           MCCn         MKn         
-----------------------------------------------------------------------------
1            1.0000       0.9998       0.9998       0.9986       0.9992       0.9999      
2            0.8562       0.9555       0.9304       0.8615       0.9075       0.9059      
3            0.9293       0.9546       0.9526       0.7500       0.8709       0.9420      
4            0.9604       0.9991       0.9875       0.9788       0.9852       0.9798      
5            0.8551       0.9995       0.9786       0.9205       0.9559       0.9273      
6            0.9675       0.9963       0.9919       0.9735       0.9843       0.9819      
Average 